### ISSUE TITLE
copy paste

### ISSUE THREAD

**Issue by peppapig450** [siduck/st#25]
How on earth do you copy paste, or how can i make it so that I can. I also cannot figure out how to change the font.
I am new to dwm and st so sorry if I am being a noob.

**Comment by siduck** [comment]
ctrl + shift + c 
ctrl + shift + v

**Comment by siduck** [comment]
to paste you can also use right click mouse/trackpad

**Comment by peppapig450** [comment]
okay so i think my vm was just trippin ill try to figure it out
