### ISSUE TITLE
about patch

### ISSUE THREAD

**Issue by n1rdeks** [siduck/st#28]
Please, give me a name of this patch - "patch_column ( doesnt cut text while resizing)"
Or path in https://st.suckless.org/patches/

Best regards.

**Comment by siduck** [comment]
> Please, give me a name of this patch - "patch_column ( doesnt cut text while resizing)" Or path in https://st.suckless.org/patches/
> 
> Best regards.

thats not the entire patch! but this is https://github.com/BeyondMagic/st/blob/master/patches/columns-rows-reflow-st-unpatched.patch

**Comment by n1rdeks** [comment]
Thanks for answer.
