### ISSUE TITLE
Xresources?

### ISSUE THREAD

**Issue by AlphaTechnolog** [siduck/st#32]
You can share your xresources to theme st?

> Like in the README.md screenshots

**Comment by siduck** [comment]
https://github.com/siduck/st/blob/main/xresources

**Comment by siduck** [comment]
this is dracula theme tho

**Comment by siduck** [comment]
the one in screenshots is onedark but onedark's base16 colors in xresources mightve confuse people so i didnt add it 

https://github.com/siduck/chadwm/blob/main/.Xresources
