### ISSUE TITLE
Xresources Issue

### ISSUE THREAD

**Issue by radstevee** [siduck/st#36]
I get this error: `'#D9E0EE': unknown terminal type.`
Also weird stuff happens with my input (can't remove letters, etc..)

This is my xressources: 
```
Xft.antialias:	1
Xft.hinting:	1
Xft.autohint:	0
Xft.hintstyle:	hintslight
Xft.rgba:	rgb
Xft.lcdfilter:	lcddefault

! window padding
st.borderpx: 20

!- 0.1 to 0.9 = transparency
st.alpha: 1.0

*background: #1E1E2E
*foreground: #D9E0EE

! Gray
*color0: #6E6C7E
*color8: #988BA2

! Red
*color1: #F28FAD
*color9: #F28FAD

! Green
*color2: #ABE9B3
*color10: #ABE9B3

! Yellow
*color3: #FAE3B0
*color11:  #FAE3B0

! Blue
*color4: #96CDFB
*color12: #96CDFB

! Mauve
*color5: #DDB6F2
*color13: #DDB6F2

! Pink
*color6: #F5C2E7
*color14: #F5C2E7

! Whites
*color7: #C3BAC6
*color15: #D9E0EE
```

**Comment by siduck** [comment]
i cant reproduce this error!

**Comment by radstevee** [comment]
i'm reinstalling anyways, maybe it'll fix it xD

**Comment by siduck** [comment]
did it fix?

**Comment by radstevee** [comment]
not really, the keyboard works but it gives me an error of #CDD6F4: unknown terminal type

**Comment by siduck** [comment]
looks like your system issue
:(

**Comment by radstevee** [comment]
Welp, it works now. I commented the foreground line out

**Comment by siduck** [comment]
@radstevee works for me tho :c

**Comment by radstevee** [comment]
just tried using xresources again, checked my $TERM env and it was set to my *foreground colour. ???. just set it to st-256color now..
