### ISSUE TITLE
Could not open input device

### ISSUE THREAD

**Issue by radstevee** [siduck/st#37]
just setting up my new T400, trying to install st, that works. but when i wanna launch it, i get this error: 
`XOpenIM failed. Could not open input device.`

**Comment by siduck** [comment]
arch u on arch?

**Comment by radstevee** [comment]
> are u on arch? 

yeah

**Comment by siduck** [comment]
try installing ttf-symbola

**Comment by radstevee** [comment]
still doesnt work

**Comment by siduck** [comment]
try libxft-bgra

**Comment by radstevee** [comment]
still not

**Comment by siduck** [comment]
can you recompile st and check?

**Comment by radstevee** [comment]
i did

**Comment by siduck** [comment]
idk then :/

**Comment by siduck** [comment]
https://unix.stackexchange.com/questions/518567/suckless-utilities-give-xopenim-failed-error

**Comment by siduck** [comment]
make sure you use en_US.utf8

**Comment by radstevee** [comment]
i use en_US.utf8

**Comment by radstevee** [comment]
fixed it somehow
