### ISSUE TITLE
Killing terminals instead of reloading them

### ISSUE THREAD

**Issue by PoSayDone** [siduck/st#41]
Hi! I'm trying to add "xrdb merge ~/.cache/wal/colors.Xresources && kill -USR1 $(pidof st)" to my bspwmrc, bspwm just killing all st windows instead of reloading colors from xresources file.

**Comment by siduck** [comment]
killall st

**Comment by PoSayDone** [comment]
> killall st
doesn't work, still just killing

fixed with making additional script with this command
```
#!/bin/zsh

xrdb merge ~/.cache/wal/colors.Xresources && kill -USR1 $(pidof st)
```
