### ISSUE TITLE
patch not working

### ISSUE THREAD

**Issue by r4vanan** [siduck/st#44]
when i try to use it with mpv . the swallowing patch is not working. even not for emacs, sxiv too. when i try to open it opening different window

**Comment by siduck** [comment]
i didnt patch swallowing patch in st

**Comment by siduck** [comment]
hmm i'll try it here

**Comment by r4vanan** [comment]
anyway thanks dude i am using alternative way to do swallow the mpv,sxiv and zathura.
`yay -S --noconfirm devour-git`
with this package  devour
like 
devour mpv vid.mp4
devour zathura book.pdf
devour sxiv pic.jpg
to automate this i add the alias to my ~.zshrc file

**Comment by siduck** [comment]
oh cool then :D

**Comment by r4vanan** [comment]
please investigate in that too. i am also try to please do that

**Comment by basilioss** [comment]
Works for me. @r4vanan try to replace this line in your dwm:
```
{ "St",               NULL,     NULL,           0,         0,          1,           0,        -1 },
```
with this:
```
{ "st",     		 NULL,     NULL,           0,         0,          1,           0,        -1 },
```

**Comment by r4vanan** [comment]
@basilioss thanks bro it works fine now
