### ISSUE TITLE
Sixel support?

### ISSUE THREAD

**Issue by elerch** [siduck/st#45]
Thanks for the great build of st. The readme says to check out the sixel branch for support on sixel graphics, but I don't see the branch. I do see activity as recently as [April 18th](https://github.com/siduck/st/pull/35). Is this an error or has the branch been removed and readme just needs updating?

**Comment by siduck** [comment]
@elerch it was hard to maintain the sixel branch as there were many bugs, Im not proficient in C either so adding it back will take a while
