### ISSUE TITLE
[Question] How did you get glyp-patch work with boxdraw

### ISSUE THREAD

**Issue by bitterhalt** [siduck/st#46]
Hello you have a nice build here!

I just wanna ask that how did you make "glyph wide support" to work with boxdraw patch? 

I can use 3rd patch from here https://st.suckless.org/patches/glyph_wide_support/
But it has some weird glyph blinking when I edit the file or move my cursor over the glyph: https://github.com/LukeSmithxyz/st/pull/349

I try to add their fix but it seems to fail if I have boxdraw installed.

With your build glyphs are working without blinking so can you link the patch that you are using. The link in your credits give me "404"

**Comment by siduck** [comment]
hi @bitterhalt i didnt use luke's build btw

**Comment by siduck** [comment]
probably that patch repo has been deleted

**Comment by bitterhalt** [comment]
Yeah I also have my own build, and I just try to figure out how to get rid of that bug. So I guess I keep searching. Thanks for the answer.

**Comment by siduck** [comment]
check this one https://github.com/AtifChy/st/blob/master/patches/0010-fix-wide-glyphs.patch
