### ISSUE TITLE
Gradient TUI bar isn't displayed correctly

### ISSUE THREAD

**Issue by basilioss** [siduck/st#47]
## Expected behavior (alacritty):

![image](https://user-images.githubusercontent.com/71596800/229116717-e3c8dd54-3e59-477b-9043-c4f434b7a99e.png)

## Current behavior (st):

![image](https://user-images.githubusercontent.com/71596800/229116875-db96245e-7ff0-4478-a4a7-2e3104b33c0a.png)

## Steps to reproduce:

1. Install [timer](https://github.com/caarlos0/timer)
2. Run `timer 15s`

**Comment by UTFeight** [comment]
Actually It does support True Color:

![image](https://github.com/siduck/st/assets/101834410/af61df60-702a-4541-9fbb-b8410f9c5974)

Only you need to set:
```shell
COLORTERM=truecolor
```

**Comment by siduck** [comment]
> That's called [True color](https://github.com/termstandard/colors)
> 
> and actually It does support that:
> 
> ![image](https://user-images.githubusercontent.com/101834410/253108048-af61df60-702a-4541-9fbb-b8410f9c5974.png)
> 
> You only need to set:
> 
> ```shell
> COLORTERM=truecolor
> ```

i never knew this, thanks a lot man
