### ISSUE TITLE
No transparency

### ISSUE THREAD

**Issue by Ved-un** [siduck/st#50]
Thank you for the project!     

I installed it recently and noticed that when using the **-n** (name) flag, terminal transparency stops working.     

What could be the problem?

**Comment by siduck** [comment]
can you show a video? make sure you have a compositor running

**Comment by Ved-un** [comment]
> can you show a video? make sure you have a compositor running    
compositor running

![flameshot_195](https://github.com/siduck/st/assets/48730277/4f35ce90-4085-4139-bff2-d6e01417c79c)

**Comment by Ved-un** [comment]
When running `st -n abc` there is no transparency, but it is still adjustable by hotkeys.    

There is no transparency only with flag **-n** (name), but with flags **-c** (class) and **-t** (title) everything is normal - there is transparency.    

Maybe the alpha patch itself is defective?       

P.S. later I will try to install my ST with the same alpha patch and check it out

**Comment by siduck** [comment]
oh, btw whats the use of st -n abc?

**Comment by Ved-un** [comment]
Well it's no use to you - but it has to work right - don't you think?     

I have a lemonbar and it displays open and closed windows and if I run for example htop I want to see htop on the panel not st.

**Comment by Ved-un** [comment]
That's what these flags are for, or did you think they were just made up?

**Comment by Ved-un** [comment]
name ... title ... class 
-n -t -c

**Comment by Ved-un** [comment]
Even if differently - in normal WM it is possible to prescribe rules for opening the application window if it is prescribed in the window rules and therefore you need these - class title name of the window...     

well now I will try another ST to realize that you are innocent )

**Comment by Ved-un** [comment]
If I write ST open centered in the rules - then all my terminal applications will open centered.... and I have a terminal player cmus and I don't want it to open in the center - that's why this flag -n or -t or -s is used to specify its name in the opening rules.

**Comment by Ved-un** [comment]
So in the rules I write for one window one thing - where it will open .... - and for the other one I write another one.    
and that WM would recognize these flags - where to open a window.

**Comment by Ved-un** [comment]
I didn't mean to offend you - but if you don't get the gist of things, I'd rather put together an ST... myself.    
People like you probably won't help me.

**Comment by Ved-un** [comment]
nah... I'm not even going to talk to you - with the same patch alpha I work fine and RAM consumes 11 mb, unlike your 24 mb.    

No, it's your fault.    
`
st & st -n ST`    

![flameshot_196](https://github.com/siduck/st/assets/48730277/5d29f328-82fa-48bd-9264-105878ad0548)

**Comment by Ved-un** [comment]
Apparently your patches are interfering with each other ...

yeah, it's nothing.... but I'd rather stay where I am and take a star off of you ... - you don't know how to put patches together in a ST vinaigrette.

**Comment by Ved-un** [comment]
okay, I'm a Russian person, so I won't take the star off ))

**Comment by siduck** [comment]
> Well it's no use to you - but it has to work right - don't you think?
> 
> I have a lemonbar and it displays open and closed windows and if I run for example htop I want to see htop on the panel not st.

st -e htop

**Comment by siduck** [comment]
you dont had to be rude tho
