### ISSUE TITLE
how to use apt-get download deb, i not find

### ISSUE THREAD

**Issue by newyorkthink** [siduck/st#58]

**Comment by siduck** [comment]
elaborate

**Comment by newyorkthink** [comment]
> elaborate

![image](https://github.com/siduck/st/assets/87791643/57de18da-4b81-4750-8764-81a7096ae305)

**Comment by newyorkthink** [comment]
st is not have like alacritty , alacritty have arch package, st don't have its

**Comment by newyorkthink** [comment]
and please make appimage fotmat file , it can run every where
the modern terminal like:
tabby, wezterm , kitty , they have appimage format

**Comment by siduck** [comment]
please read the dependencies  & install section in readme
