### ISSUE TITLE
Bug: the st window won't close on Wayland

### ISSUE THREAD

**Issue by rdbo** [siduck/st#63]
compositor: river (master)
OS: alpine linux

I am investigating this issue and will attempt to fix it.
Initially I thought it could've been an issue with my compositor, but the "close" action is done directly by wlroots/XWayland. And standard st doesn't have this issue. This doesn't discard the possibility that wlroots might be at fault though.
I noticed that this happens after a call to `sigchld`, which makes sense since I just signalled for the process to close the window. But after going through `sigchld`, the program gets stuck at `exit`, with some calls related to a pthread mutex? Not sure yet what it is.
If I figure out and fix it, I will do a PR

**Comment by rdbo** [comment]
This seems to have something to do with the signalling. I disabled the SIGCHLD when the X window gets deleted, and the terminal no longer fails to close.
I won't do a PR yet because I want to figure out why it doesn't `die()` gracefully with the regular SIGCHLD (and perhaps find another solution)

**Comment by siduck** [comment]
st is supposed to work well  in xorg
