### ISSUE TITLE
issue: icons do not get fully loaded inside st using nvchad

### ISSUE THREAD

**Issue by arztareef** [siduck/st#65]
Hello there, siduck. I am arztareef, a great admirer of your work (both NvChad and chadwm). I have been using st as my terminal emulator since I started linux and just now I have found this issue. The icons do not get fully loaded in when i open up nvim tree using nvchad. All the other other terminal emulator like alacritty and kitty works but only this build of st can fully render the icons. I would like to know what you did to accomplish this.

The issue: 
![image](https://github.com/siduck/st/assets/162489150/4a5224a2-42ca-42db-b6d8-43f0dcd6c7b6)

**Comment by siduck** [comment]
![image](https://github.com/siduck/st/assets/59060246/e77c058b-a1cb-4274-bcbe-72d1f35985b5)

doesnt happen here,  i hope you're using latest build of this repo and jetbrains nerd font is latest too ( as this font's mentioned in Xresources )

**Comment by arztareef** [comment]
no sir, i am not referring to your build, i was referring to my build.

Every st build but your one have that icon loading issue. Only your one has no problem whatsoever.

I would like to know what you have done to accomplish that :)

**Comment by siduck** [comment]
there's a patch wide glyphs one , try it

**Comment by siduck** [comment]
https://st.suckless.org/patches/glyph_wide_support/

**Comment by siduck** [comment]
> may i please ask how you have implemented the patch (before adding ligatures or boxdraw or after), my build of st is breaking when im trying to apply the patch. my build of st (https://codeberg.org/arztareef/st)

i added it after all major patches

**Comment by arztareef** [comment]
i fixed it after manipulating smoe codes, thanks siduck! irdk how i can repay you back lol

idk, have my dwm and st build which got highly inspired by you xd:
https://codeberg.org/arztareef/dwm
https://codeberg.org/arztareef/st

**Comment by zakarriyah** [comment]
@arztareef as-salamu alaykum brother, remove that `they/them` thing from your bio

**Comment by arztareef** [comment]
> @arztareef as-salamu alaykum brother, remove that `they/them` thing from your bio. We have it like the lg 📺 people

walaikumassalam, thank you for telling me brother! 😄

**Comment by zakarriyah** [comment]
> > @arztareef as-salamu alaykum brother, remove that `they/them` thing from your bio. We have it like the lg 📺 people
> 
> walaikumassalam, thank you for telling me brother! 😄

so you added the they/them just as a joke? :grimacing:  , ive to talk from this account or else i'll be  cancelled on github
