### ISSUE TITLE
[help] Gaps around st terminal

### ISSUE THREAD

**Issue by arztareef** [siduck/st#66]
Hulloa there, siduck! I have figured out another issue with my patch of st terminal (https://codeberg.org/st). There is seem to have some awkward gaps around my patch of st while using neovim and other TUI(s.) utility. I am dropping a picture depicting the problem. I have tried other forks of ST Terminal and it appears that they also go through the same issue **except** _yours._I would really appreciate it how you went around and fixed this.
![png](https://github.com/siduck/st/assets/162489150/1502fb4e-86d9-4066-a2c1-c5a9fb5b219b)

**Comment by siduck** [comment]
remove padding from st? borderpx from your .Xresources

**Comment by arztareef** [comment]
yea no the padding is set to 0 px

**Comment by siduck** [comment]
idk then, i dont face this issue
